### ISSUE TITLE
Create an autoloader

### ISSUE THREAD

**Issue by horiafb** [Ioana-Ionel/BookReviewPHP#2]
Currently you are including the your project files with the [`include` directive](https://github.com/Ioana-Ionel/BookReviewPHP/blob/master/src/Api/Controllers/ReaderController.php#L8).

Let us move towards [composer](https://getcomposer.org/) :) 
You will need to install composer and afterwards create a composer.json file in the root of your project, with this you will also define the autoloader and the namespace for it.
As composer and the autoloading process is a pretty important component of php development, please read about it and try to understand how to write a minimal composer.json file.
For the autoloader we will be using the [PSR-4 standard](https://www.php-fig.org/psr/psr-4/)

Don't forget to ask any questions that come to mind. (and I mean any at any time, here or on skype, I will reply)

**Comment by Ioana-Ionel** [comment]
Done
